# Generated by Django 3.2 on 2021-04-27 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student',
        ),
    ]
