# Generated by Django 3.2 on 2021-04-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_delete_student'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_number', models.CharField(default='123', max_length=8, verbose_name='学号')),
                ('name', models.CharField(max_length=256, verbose_name='姓名')),
                ('password', models.CharField(default='123', max_length=128, verbose_name='密码')),
                ('grade', models.CharField(choices=[('one', '大一'), ('two', '大二'), ('three', '大三'), ('four', '大四')], max_length=5, verbose_name='年级')),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女')], default='男', max_length=6, verbose_name='性别')),
                ('email', models.EmailField(max_length=50, verbose_name='邮箱')),
                ('major', models.CharField(max_length=10, verbose_name='专业名称')),
            ],
        ),
    ]
