# Generated by Django 3.2 on 2021-05-07 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_teacher'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='student_number',
            new_name='Teacher_number',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='major',
        ),
    ]
