# Generated by Django 3.2 on 2021-05-13 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20210507_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='test_questions',
            options={'ordering': ('Question_number',), 'verbose_name': '单项选择题库', 'verbose_name_plural': '单项选择题库'},
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
