# Generated by Django 3.2 on 2021-05-17 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210513_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_questions',
            name='level',
            field=models.CharField(choices=[('general', 'general'), ('easy', 'easy'), ('difficult', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
