# Generated by Django 3.2 on 2021-05-17 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_alter_test_questions_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_questions',
            name='level',
            field=models.CharField(choices=[('difficult', 'difficult'), ('general', 'general'), ('easy', 'easy')], max_length=10, verbose_name='等级'),
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=20, verbose_name='科目')),
                ('major', models.CharField(max_length=20, verbose_name='考卷适用专业')),
                ('examtime', models.DateTimeField()),
                ('pid', models.ManyToManyField(to='student.Test_Questions')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.teacher')),
            ],
            options={
                'verbose_name': '试卷',
                'verbose_name_plural': '试卷',
                'db_table': 'paper',
            },
        ),
    ]
