# Generated by Django 3.2 on 2021-05-20 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_auto_20210517_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test_questions',
            name='answer',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=512, verbose_name='答案'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='level',
            field=models.CharField(choices=[('general', 'general'), ('difficult', 'difficult'), ('easy', 'easy')], max_length=10, verbose_name='等级'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='optionA',
            field=models.CharField(max_length=512, verbose_name='A选项'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='optionB',
            field=models.CharField(max_length=512, verbose_name='B选项'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='optionC',
            field=models.CharField(max_length=512, verbose_name='C选项'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='optionD',
            field=models.CharField(max_length=512, verbose_name='D选项'),
        ),
        migrations.AlterField(
            model_name='test_questions',
            name='subject',
            field=models.CharField(max_length=512, verbose_name='科目'),
        ),
    ]
